// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'pref-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'zotero-chat-section-header'
  | 'zotero-chat-section-sidenav';
