// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apikey": string;
      "model": string;
      "baseurl": string;
      "temperature": string;
      "maxiterations": string;
    };
  }
}
